import type { Metadata } from 'next'
import { Montserrat, Zen_Kaku_Gothic_Antique } from 'next/font/google'

import { SITE_NAME } from '@/constants/seo.constants'

import './globals.scss'
import Providers from './providers'

const zen = Zen_Kaku_Gothic_Antique({
	subsets: ['cyrillic'],
	weight: ['400', '500', '700'],
	display: 'swap',
	variable: '--font-zen',
	style: ['normal']
})

const mont = Montserrat({
	subsets: ['cyrillic'],
	weight: ['400', '500', '700'],
	display: 'swap',
	variable: '--font-mont',
	style: ['normal']
})

export const metadata: Metadata = {
	title: {
		default: SITE_NAME,
		template: `%s | ${SITE_NAME}`
	},
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='ru'
			className={`${zen.variable} ${mont.variable}`}
		>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
