import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { Ubuntu } from 'next/font/google'

import { SITE_NAME } from '@/constants/seo.constants'

import './globals.scss'
import Providers from './providers'

const fontPrimary = Ubuntu({
	subsets: ['cyrillic'],
	weight: ['400', '500', '700'],
	display: 'swap',
	variable: '--font-primary',
	style: ['normal']
})

export const metadata: Metadata = {
	title: {
		default: SITE_NAME,
		template: `%s | ${SITE_NAME}`
	},
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children,
	params: { locale }
}: Readonly<{
	children: React.ReactNode
	params: { locale: string }
}>) {
	const messages = await getMessages()

	return (
		<html
			lang={locale}
			className={`${fontPrimary.variable}`}
		>
			<body>
				<NextIntlClientProvider messages={messages}>
					<Providers>{children}</Providers>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
